In [3]:
import pandas as pd
import numpy as np
# Sample dataset
data = pd.DataFrame({
'OriginalFeature': [1, 2, 3, 4, 5, 6, 7],
'CategoricalFeature': ['A', 'B', 'A', 'B', 'A', 'B', 'A']
})
data

   OriginalFeature CategoricalFeature
0                1                  A
1                2                  B
2                3                  A
3                4                  B
4                5                  A
5                6                  B
6                7                  A

In [7]:
# One-hot Encoding 
data1 = pd.get_dummies(data,columns=['CategoricalFeature'])
data1

   OriginalFeature  CategoricalFeature_A  CategoricalFeature_B
0                1                  True                 False
1                2                 False                  True
2                3                  True                 False
3                4                 False                  True
4                5                  True                 False
5                6                 False                  True
6                7                  True                 False

In [10]:
data2 = pd.get_dummies(data,columns=['CategoricalFeature'],drop_first=True)
data2

   OriginalFeature  CategoricalFeature_B
0                1                 False
1                2                  True
2                3                 False
3                4                  True
4                5                 False
5                6                  True
6                7                 False

In [20]:
import pandas as pd
df=pd.read_csv("car data.csv")
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [23]:
df.drop('Car_Name',axis=1,inplace=True) #drop Car_Name Column

In [24]:
df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [25]:
df.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [26]:
pd.get_dummies(df)

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,2014,3.35,5.59,27000,0,False,False,True,True,False,False,True
1,2013,4.75,9.54,43000,0,False,True,False,True,False,False,True
2,2017,7.25,9.85,6900,0,False,False,True,True,False,False,True
3,2011,2.85,4.15,5200,0,False,False,True,True,False,False,True
4,2014,4.60,6.87,42450,0,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,False,True,False,True,False,False,True
297,2015,4.00,5.90,60000,0,False,False,True,True,False,False,True
298,2009,3.35,11.00,87934,0,False,False,True,True,False,False,True
299,2017,11.50,12.50,9000,0,False,True,False,True,False,False,True
300,2016,5.30,5.90,5464,0,False,False,True,True,False,False,True

In [28]:
df=pd.get_dummies(df,drop_first=True)
df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,3.35,5.59,27000,0,False,True,False,True
1,2013,4.75,9.54,43000,0,True,False,False,True
2,2017,7.25,9.85,6900,0,False,True,False,True
3,2011,2.85,4.15,5200,0,False,True,False,True
4,2014,4.60,6.87,42450,0,True,False,False,True

## adding new feature

In [32]:
import pandas as pd
#defining features
room_length = [18, 20, 10, 12, 18, 11]
room_breadth = [20, 20, 10, 11, 19, 10]
room_type = ['Big', 'Big', 'Normal', 'Normal', 'Big', 'Normal']
#creating a data frame
data = pd.DataFrame({'Length': room_length, 'Breadth': room_breadth, 'Type': room_type})
data

   Length  Breadth    Type
0      18       20     Big
1      20       20     Big
2      10       10  Normal
3      12       11  Normal
4      18       19     Big
5      11       10  Normal

In [33]:
#Adding a feature called area from length and breadth
data['Area'] = data['Length'] * data['Breadth']
data

   Length  Breadth    Type  Area
0      18       20     Big   360
1      20       20     Big   400
2      10       10  Normal   100
3      12       11  Normal   132
4      18       19     Big   342
5      11       10  Normal   110

In [37]:
data[data['Area']>333]

   Length  Breadth Type  Area
0      18       20  Big   360
1      20       20  Big   400
4      18       19  Big   342

## Encoding nominal variable

In [38]:
import pandas as pd
age = [18, 20, 23, 19, 18, 22]
city = ['City A', 'City B', 'City B', 'City A', 'City C', 'City B']
#Creating a data frame
data1 = pd.DataFrame({'age': age, 'city': city})
data1

   age    city
0   18  City A
1   20  City B
2   23  City B
3   19  City A
4   18  City C
5   22  City B

In [40]:
#get_dummies function of pandas library can be used to dummy code categorical variables
df1=pd.get_dummies(data1)
df1

   age  city_City A  city_City B  city_City C
0   18         True        False        False
1   20        False         True        False
2   23        False         True        False
3   19         True        False        False
4   18        False        False         True
5   22        False         True        False

In [42]:
#drop_first will remove first column of three categories
df2=pd.get_dummies(data1, drop_first=True)
df2

   age  city_City B  city_City C
0   18        False        False
1   20         True        False
2   23         True        False
3   19        False        False
4   18        False         True
5   22         True        False

## Transforming Numeric (continuous) Features to Categorical Features

In [50]:
import pandas as pd
#Defining features
apartment_area=[4720, 2430, 4368, 3969, 6142, 7912]
apartment_price=[2360000, 1215000, 2184000, 1984500, 3071000,3956000]
#Creating a data frame
data=pd.DataFrame({'Area': apartment_area, 'Price': apartment_price})
data

   Area    Price
0  4720  2360000
1  2430  1215000
2  4368  2184000
3  3969  1984500
4  6142  3071000
5  7912  3956000

In [53]:
import numpy as np
data['Price'] = np.where(data ['Price'] > 3000000, 'High', np.where(data['Price'] < 2000000 ,'low',"Mid"))
data

   Area Price
0  4720   Mid
1  2430   low
2  4368   Mid
3  3969   low
4  6142  High
5  7912  High

In [55]:
#Understanding the use of where function of numpy
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8])
x= np.where(arr%2== 1, 'Odd', 'Even')
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']

In [57]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8,9.5,11.3])
x= np.where(arr%2== 1, 'Odd',np.where(arr%2== 0, 'Even', 'Mid'))
print(arr)
print(x)

[ 1.   2.   3.   4.   5.   6.   7.   8.   9.5 11.3]
['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Mid' 'Mid']

In [58]:
from sklearn.model_selection import train_test_split

x=[[i] for i in range(1,21)]
y=[10,20,25,35,45,50,60,65,70,80,85,90,95,100,105,110,115,120,125,130]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
print("X_Train:",x_train)
print("X_Test:",x_test)

X_Train: [[6], [12], [4], [19], [17], [14], [3], [10], [20], [5], [13], [8], [11], [15], [7]]
X_Test: [[1], [18], [16], [2], [9]]

In [59]:
import pandas as pd
df=pd.read_csv("auto-mpg.csv")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [64]:
x=df[["horsepower",'acceleration','mpg']]
y=df['cylinders']

In [66]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
print("X_Train: Shape",x_train.shape)
print("X_Test: Shape",x_test.shape)
print("Y_Train: Shape",y_train.shape)
print("Y_Test: Shape",y_test.shape)

X_Train: Shape (298, 3)
X_Test: Shape (100, 3)
Y_Train: Shape (298,)
Y_Test: Shape (100,)

In [67]:
x_train.head()

    horsepower  acceleration   mpg
245         66          14.4  36.1
110         94          16.5  22.0
16          97          15.5  18.0
66         150          11.5  17.0
153        105          16.0  18.0

In [83]:
x_test.head()

    horsepower  acceleration   mpg
198         53          17.4  33.0
396         79          18.6  28.0
33         100          13.0  19.0
208        150          13.2  13.0
93         150          14.5  14.0