In [9]:
import requests
from bs4 import BeautifulSoup

soup=BeautifulSoup(open("Popular_Quotes.html","r",encoding="utf-8"))
# print(soup.prettify())

In [10]:
quoteText=[]
author=[]
for i in soup.find_all("div" ,class_="quoteText"):
    quoteText.append(i.get_text(strip=True).split("―")[0])
    author.append(i.get_text(strip=True).split("―")[1])

In [11]:
like=[]
for i in soup.find_all("a" ,class_="smallText"):
    like.append(i.get_text(strip=True).split("likes")[0])

In [19]:
import pandas as pd
df=pd.DataFrame({"quote":quoteText,"author":author,"like":like})
df

,quote,author,like
0,“Be yourself; everyone else is already taken.”,Oscar Wilde,172090
1,"“I'm selfish, impatient and a little insecure....",Marilyn Monroe,162993
2,"“So many books, so little time.”",Frank Zappa,147069
3,“Two things are infinite: the universe and hum...,Albert Einstein,146082
4,“A room without books is like a body without a...,Marcus Tullius Cicero,133363
5,"“Be who you are and say what you feel, because...",Bernard M. Baruch,128599
6,“You've gotta dance like there's nobody watchi...,William W. Purkey,127116
7,“You know you're in love when you can't fall a...,Dr. Seuss,124987
8,"“You only live once, but if you do it right, o...",Mae West,117240
9,“Be the change that you wish to see in the wor...,Mahatma Gandhi,113213
10,“In three words I can sum up everything I've l...,Robert Frost,108002
11,"“If you want to know what a man's like, take a...","J.K. Rowling,Harry Potter and the Goblet of Fire",100983
12,“Don’t walk in front of me… I may not followDo...,Albert Camus,92274
13,"“If you tell the truth, you don't have to reme...",Mark Twain,90869
14,“Friendship ... is born at the moment when one...,"C.S. Lewis,The Four Loves",87553
15,“I've learned that people will forget what you...,Maya Angelou,87398
16,“A friend is someone who knows all about you a...,Elbert Hubbard,83514
17,“To live is the rarest thing in the world. Mos...,Oscar Wilde,83168
18,“Always forgive your enemies; nothing annoys t...,Oscar Wilde,80923
19,“Darkness cannot drive out darkness: only ligh...,"Martin Luther King Jr.,A Testament of Hope: Th...",77451
20,“Live as if you were to die tomorrow. Learn as...,Mahatma Gandhi,77061
21,“We accept the love we think we deserve.”,"Stephen Chbosky,The Perks of Being a Wallflower",74875
22,"“Without music, life would be a mistake.”","Friedrich Nietzsche,Twilight of the Idols",73251
23,“I am so clever that sometimes I don't underst...,"Oscar Wilde,The Happy Prince and Other Stories",71126
24,“To be yourself in a world that is constantly ...,Ralph Waldo Emerson,69009
25,“Here's to the crazy ones. The misfits. The re...,Steve Jobs,67728
26,"“Insanity is doing the same thing, over and ov...",Narcotics Anonymous,64173
27,“I believe that everything happens for a reaso...,Marilyn Monroe,61795
28,“It is better to be hated for what you are tha...,"Andre Gide,Autumn Leaves",61028
29,“Twenty years from now you will be more disapp...,"H. Jackson Brown Jr.,P.S. I Love You",59792

In [20]:
df.sort_values(by="like")

,quote,author,like
11,"“If you want to know what a man's like, take a...","J.K. Rowling,Harry Potter and the Goblet of Fire",100983
10,“In three words I can sum up everything I've l...,Robert Frost,108002
9,“Be the change that you wish to see in the wor...,Mahatma Gandhi,113213
8,"“You only live once, but if you do it right, o...",Mae West,117240
7,“You know you're in love when you can't fall a...,Dr. Seuss,124987
6,“You've gotta dance like there's nobody watchi...,William W. Purkey,127116
5,"“Be who you are and say what you feel, because...",Bernard M. Baruch,128599
4,“A room without books is like a body without a...,Marcus Tullius Cicero,133363
3,“Two things are infinite: the universe and hum...,Albert Einstein,146082
2,"“So many books, so little time.”",Frank Zappa,147069
1,"“I'm selfish, impatient and a little insecure....",Marilyn Monroe,162993
0,“Be yourself; everyone else is already taken.”,Oscar Wilde,172090
29,“Twenty years from now you will be more disapp...,"H. Jackson Brown Jr.,P.S. I Love You",59792
28,“It is better to be hated for what you are tha...,"Andre Gide,Autumn Leaves",61028
27,“I believe that everything happens for a reaso...,Marilyn Monroe,61795
26,"“Insanity is doing the same thing, over and ov...",Narcotics Anonymous,64173
25,“Here's to the crazy ones. The misfits. The re...,Steve Jobs,67728
24,“To be yourself in a world that is constantly ...,Ralph Waldo Emerson,69009
23,“I am so clever that sometimes I don't underst...,"Oscar Wilde,The Happy Prince and Other Stories",71126
22,"“Without music, life would be a mistake.”","Friedrich Nietzsche,Twilight of the Idols",73251
21,“We accept the love we think we deserve.”,"Stephen Chbosky,The Perks of Being a Wallflower",74875
20,“Live as if you were to die tomorrow. Learn as...,Mahatma Gandhi,77061
19,“Darkness cannot drive out darkness: only ligh...,"Martin Luther King Jr.,A Testament of Hope: Th...",77451
18,“Always forgive your enemies; nothing annoys t...,Oscar Wilde,80923
17,“To live is the rarest thing in the world. Mos...,Oscar Wilde,83168
16,“A friend is someone who knows all about you a...,Elbert Hubbard,83514
15,“I've learned that people will forget what you...,Maya Angelou,87398
14,“Friendship ... is born at the moment when one...,"C.S. Lewis,The Four Loves",87553
13,"“If you tell the truth, you don't have to reme...",Mark Twain,90869
12,“Don’t walk in front of me… I may not followDo...,Albert Camus,92274